import { Category } from "./types";
import {
  Dog,
  Pizza,
  Globe,
  Briefcase,
  Dumbbell,
  Lamp,
  Trophy,
  Star,
  ShoppingBag,
  type LucideIcon,
} from "lucide-react";

export const GAME_WORDS: Record<Category, string[]> = {
  animales: [
    "Conejo",
    "León",
    "Elefante",
    "Pingüino",
    "Delfín",
    "Águila",
    "Oso",
    "Jirafa",
    "Cocodrilo",
    "Tortuga",
    "Tiburón",
    "Mariposa",
    "Canguro",
    "Panda",
    "Tigre",
    "Búho",
    "Serpiente",
    "Caballo",
    "Ballena",
    "Lobo",
    "Zorro",
    "Rinoceronte",
    "Hipopótamo",
    "Koala",
    "Gorila",
    "Flamenco",
    "Pulpo",
    "Foca",
    "Loro",
    "Leopardo",
  ],
  comida: [
    "Pizza",
    "Hamburguesa",
    "Sushi",
    "Tacos",
    "Pasta",
    "Helado",
    "Empanada",
    "Asado",
    "Milanesa",
    "Ensalada",
    "Paella",
    "Risotto",
    "Curry",
    "Croissant",
    "Falafel",
    "Burrito",
    "Ramen",
    "Ceviche",
    "Dulce de leche",
    "Choripán",
    "Alfajor",
    "Mate",
    "Chivito",
    "Locro",
    "Humita",
    "Ravioles",
    "Ñoquis",
    "Chimichurri",
    "Provoleta",
    "Fainá",
  ],
  paises: [
    "Argentina",
    "Brasil",
    "Uruguay",
    "España",
    "Italia",
    "Francia",
    "Japón",
    "China",
    "México",
    "Alemania",
    "India",
    "Canadá",
    "Australia",
    "Egipto",
    "Grecia",
    "Perú",
    "Chile",
    "Colombia",
    "Portugal",
    "Noruega",
    "Suecia",
    "Rusia",
    "Turquía",
    "Marruecos",
    "Inglaterra",
    "Corea del Sur",
    "Tailandia",
    "Holanda",
    "Suiza",
    "Bélgica",
  ],
  profesiones: [
    "Doctor",
    "Ingeniero",
    "Profesor",
    "Chef",
    "Arquitecto",
    "Abogado",
    "Enfermero",
    "Programador",
    "Diseñador",
    "Mecánico",
    "Electricista",
    "Músico",
    "Actor",
    "Periodista",
    "Fotógrafo",
    "Veterinario",
    "Bombero",
    "Policía",
    "Piloto",
    "Carpintero",
    "Contador",
    "Psicólogo",
    "Dentista",
    "Plomero",
    "Pintor",
    "Escritor",
    "Bailarín",
    "Chef Pastelero",
    "Científico",
    "Agricultor",
    "Reparador",
  ],
  deportes: [
    "Fútbol",
    "Basquetbol",
    "Tenis",
    "Natación",
    "Voleibol",
    "Rugby",
    "Golf",
    "Atletismo",
    "Ciclismo",
    "Boxeo",
    "Hockey",
    "Béisbol",
    "Surf",
    "Esquí",
    "Escalada",
    "Yoga",
    "Gimnasia",
    "Ping Pong",
    "Paddle",
    "Karate",
    "Judo",
    "Taekwondo",
    "Crossfit",
    "Snowboard",
    "Skate",
    "Polo",
    "Handball",
    "Waterpolo",
    "Esgrima",
    "Arquería",
  ],
  objetos: [
    "Celular",
    "Libro",
    "Silla",
    "Mesa",
    "Lámpara",
    "Reloj",
    "Llave",
    "Botella",
    "Mochila",
    "Cuaderno",
    "Tijeras",
    "Espejo",
    "Almohada",
    "Paraguas",
    "Cámara",
    "Audífonos",
    "Teclado",
    "Gafas",
    "Billetera",
    "Cepillo",
    "Computadora",
    "Mouse",
    "Ventilador",
    "Termo",
    "Mate",
    "Bombilla",
    "Guitarra",
    "Micrófono",
    "Control Remoto",
    "Cargador",
  ],
  futbol: [
    // Leyendas Argentinas
    "Maradona",
    "Messi",
    "Alfredo Di Stéfano",
    "Gabriel Batistuta",
    "Juan Román Riquelme",
    "Javier Mascherano",
    "Sergio Agüero",
    "Ángel Di María",
    "Carlos Tevez",
    "Hernán Crespo",
    "Claudio Caniggia",
    "Oscar Ruggeri",
    "Javier Zanetti",
    "Ariel Ortega",
    "Sergio Romero",
    "Emiliano Sala",
    "Juan Sebastián Verón",
    "Pablo Aimar",
    "Martín Palermo",
    "Marcelo Bielsa",
    "Carlos Bilardo",
    "César Luis Menotti",
    // Leyendas Uruguayas
    "Luis Suárez",
    "Diego Forlán",
    "Edinson Cavani",
    "Rodrigo Bentancur",
    "Óscar Tabárez",
    "Enzo Francescoli",
    "Diente Lopez",
    "Sebastian Coates",
    "Leo Fernandez",
    "Walter Gargano",
    "Cacha Arevalo Rios",
    "Diego Godín",
    "Álvaro Recoba",
    "Obdulio Varela",
    "Fernando Muslera",
    "Sebastián Abreu",
    "Diego Lugano",
    "Martín Cáceres",
    "Federico Valverde",
    "Darwin Núñez",
    // Leyendas Mundiales
    "Pelé",
    "Cristiano Ronaldo",
    "Zinedine Zidane",
    "Johan Cruyff",
    "Franz Beckenbauer",
    "Ronaldinho",
    "Ronaldo Nazário",
    "Roberto Baggio",
    "Paolo Maldini",
    "Thierry Henry",
    "Xavi Hernández",
    "Andrés Iniesta",
    "Sergio Ramos",
    "Iker Casillas",
    "Luka Modrić",
    "Karim Benzema",
    "Kylian Mbappé",
    "Neymar",
    "Robert Lewandowski",
    "Erling Haaland",
    "Kevin De Bruyne",
    "Mohamed Salah",
    "Harry Kane",
    "Virgil van Dijk",
    // Directores Técnicos
    "José Mourinho",
    "Celso Otero",
    "Pep Guardiola",
    "Carlo Ancelotti",
    "Jürgen Klopp",
    "Diego Simeone",
    "Diego Aguirre",
    "Zinedine Zidane",
    "Alex Ferguson",
    "Arsène Wenger",
  ],
  celebridades: [
    // Argentinas/Uruguayas
    "Ricardo Darín",
    "Natalia Oreiro",
    "Gustavo Cerati",
    "Soda Stereo",
    "Diego Torres",
    "Tini Stoessel",
    "Paulo Londra",
    "Jorge Drexler",
    "Fito Páez",
    "Charly García",
    "Andrés Calamaro",
    "Mercedes Sosa",
    "Susana Giménez",
    "Mirtha Legrand",
    "Guillermo Francella",
    "No Te Va Gustar",
    // Mundiales
    "Shakira",
    "Taylor Swift",
    "Bad Bunny",
    "Justin Bieber",
    "LeBron James",
    "Will Smith",
    "Jennifer Lopez",
    "Leonardo DiCaprio",
    "Beyoncé",
    "Rihanna",
    "Ed Sheeran",
    "Ariana Grande",
    "Dua Lipa",
    "The Weeknd",
    "Drake",
    "Bruno Mars",
  ],
  marcas: [
    "Nike",
    "Adidas",
    "Apple",
    "Samsung",
    "Coca-Cola",
    "Pepsi",
    "McDonald's",
    "Starbucks",
    "Toyota",
    "Mercedes-Benz",
    "Sony",
    "Microsoft",
    "Amazon",
    "Google",
    "Ferrari",
    "Gucci",
    "Rolex",
    "Disney",
    "Netflix",
    "Spotify",
    "Havanna",
    "Portezuelo",
    "Puma",
    "BMW",
    "Volkswagen",
    "Ford",
    "Honda",
    "Yamaha",
    "PlayStation",
    "Xbox",
  ],
};

export const CATEGORY_LABELS: Record<Category, string> = {
  animales: "Animales",
  comida: "Comida",
  paises: "Países",
  profesiones: "Profesiones",
  deportes: "Deportes",
  objetos: "Objetos",
  futbol: "Fútbol",
  celebridades: "Celebridades",
  marcas: "Marcas",
};

export const CATEGORY_ICONS: Record<Category, LucideIcon> = {
  animales: Dog,
  comida: Pizza,
  paises: Globe,
  profesiones: Briefcase,
  deportes: Dumbbell,
  objetos: Lamp,
  futbol: Trophy,
  celebridades: Star,
  marcas: ShoppingBag,
};
